notifications:
  email:
    - laszewski@gmail.com
    - shenoy.200@gmail.com
    - vaglomangirish@gmail.com
    - kevinwangfg@gmail.com
    
git:
  submodules: false

virtualenv:
  system_site_packages: true

#os:
#  - linux
#  - osx

language: python

python:
  - "2.7"

# libraries:
# - name: pycrypto
#   version: "2.6.1"
  
install:
  - pip install --upgrade pip
  - pip --version
  - curl -L http://ftp.dlitz.net/pub/dlitz/crypto/pycrypto/pycrypto-2.6.1.tar.gz | tar xz
  - cd pycrypto-2.6.1
  - python setup.py install
  - cd ~
  - mkdir ~/.cloudmesh
  - mkdir -p github/cloudmesh
  - cd github/cloudmesh
  - git clone https://github.com/cloudmesh/base.git
  - git clone https://github.com/cloudmesh/client.git
  - cd base
  - pip install -r requirements.txt
  - pip install .
  - cd ../client
  - pip install -r requirements.txt
  - pip install -r requirements-doc.txt
  - pip install .
  - ln -s `pwd` $(dirname `which python`)/../lib/python2.7/site-packages/cloudmesh_client

script:
  - nosetests -v --nocapture tests/test_pass.py
  - nosetests -v --nocapture tests/test_configdict.py
  - nosetests -v --nocapture tests/test_default.py
  - nosetests -v --nocapture tests/test_flatdict.py
  - nosetests -v --nocapture tests/test_model.py
  - nosetests -v --nocapture tests/test_shell.py
  - nosetests -v --nocapture tests/test_tables.py
  - make doc
  - cm help
