sudo: required
dist: trusty

notifications:
  email:
    - laszewski@gmail.com
    - kevinwangfg@gmail.com

before_install:
  - echo "- UPGRADE -----------"
  - sudo apt-get -o Dpkg::Options::='--force-confold' --force-yes -fuy dist-upgrade
  - echo "- BEFORE INSTALL -----------"
  - sudo apt-get install -y autotools-dev
  - sudo apt-get install -y blt-dev
  - sudo apt-get install -y bzip2
  - sudo apt-get install -y dpkg-dev
  - sudo apt-get install -y g++-multilib
  - sudo apt-get install -y gcc-multilib
  - sudo apt-get install -y libbluetooth-dev
  - sudo apt-get install -y libbz2-dev
  - sudo apt-get install -y libexpat1-dev
  - sudo apt-get install -y libffi-dev
  - sudo apt-get install -y libffi6
  - sudo apt-get install -y libffi6-dbg
  - sudo apt-get install -y libgdbm-dev
  - sudo apt-get install -y libgpm2
  - sudo apt-get install -y libncursesw5-dev
  - sudo apt-get install -y libreadline-dev
  - sudo apt-get install -y libsqlite3-dev
  - sudo apt-get install -y libssl-dev
  - sudo apt-get install -y libtinfo-dev
  - sudo apt-get install -y mime-support
  - sudo apt-get install -y net-tools
  - sudo apt-get install -y netbase
  - sudo apt-get install -y python-crypto
  - sudo apt-get install -y python-mox3
  - sudo apt-get install -y python-pil
  - sudo apt-get install -y python-ply
  - sudo apt-get install -y quilt
  - sudo apt-get install -y tk-dev
  - sudo apt-get install -y zlib1g-dev
  # - cd /tmp
  - wget http://www.python.org/ftp/python/2.7.12/Python-2.7.12.tgz
  - tar xzvf Python-2.7.12.tgz
  - cd Python-2.7.12
  - ./configure --enable-shared > python-install.log 2>&1
  - sudo make >> python-install.log 2>&1
  - sudo make install >> python-install.log 2>&1
  - sudo pip install backports.ssl_match_hostname
  - cd ..
  - echo "-----------------------------"

addons:
  apt:
    packages:
      - python-dev
      - python-simplejson

git:
  submodules: false

virtualenv:
  system_site_packages: true

#os:
#  - linux
#  - osx

language: python

python:
  - "2.7"

install:
  - pwd
  - ls
  # - export PATH="/opt/python/2.7.10/bin:$PATH"
  - echo $PATH
  - sudo pip install --upgrade pip
  - which python
  - python --version
  - pip --version
  - mkdir ~/.cloudmesh
  - sudo pip install pyyaml --upgrade --force
  - sudo pip install lockfile
  - curl -L http://ftp.dlitz.net/pub/dlitz/crypto/pycrypto/pycrypto-2.6.1.tar.gz | tar xz
  - cd pycrypto-2.6.1
  - python setup.py install
  - cd ..
  - pwd
  - ls
  - pip install pip -U
  - python --version
  - pip --version
  # - git clone https://github.com/cloudmesh/client.git
  # - cd client
  - pip install -U -r requirements.txt
  - pip install -U -r requirements-doc.txt
  - pip install -U -r requirements-test.txt
  - pip install -U .

script:
  - pwd
  - ls
  - cat /home/travis/virtualenv/python2.7_with_system_site_packages/bin/cm
  - cm version
  - pip install nose
  - nosetests -v --nocapture tests/cm_basic
#  -  py.test tests/cm_basic
#  - make doc
#  - cm help

